name: Docker CI/CD Setup

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub now
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./fastapi-backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fastapi-backend:latest

  build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./nextjs-frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nextjs-frontend:latest
        